jwt:
  secret-key: "ThisIsMySuperSecretKeyForJWTAuthentication123456789"
  expiration: 300000
logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
spring:
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
    application:
      name: USER-SERVICE
    profiles:
      active: dev
    config:
      import: optional:configserver:http://localhost:8084

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

aws:
  region: ap-south-1
  s3:
    bucket-name: "spring-boot-microservice-application"