server:
  servlet:
    context-path: "/api/v1"
jwt:
  secret-key: "ThisIsMySuperSecretKeyForJWTAuthentication123456789"
  expiration: 300000
spring:
  application:
    name: HOTEL-SERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8084
