server:
  servlet:
    context-path: "/api/v1"
jwt:
  secret-key: "ThisIsMySuperSecretKeyForJWTAuthentication123456789"
  expiration: 300000
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  application:
    name: HOTEL-SERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8084
aws:
  region: ap-south-1
  s3:
    bucket-name: "spring-boot-microservice-application"