package com.microservices.paymentservice.enums;

public enum ErrorCode {
    PAYMENT_NOT_FOUND_EXCEPTION,
    PAYMENT_ALREADY_EXISTS_EXCEPTION,
    PAYMENT_ALREADY_REFUNDED_EXCEPTION,
    PAYMENT_CANNOT_BE_REFUNDED_EXCEPTION,
    METHOD_ARGUMENT_NOT_VALID_EXCEPTION,
    CONSTRAINT_VIOLATION_EXCEPTION,
    GENERIC_EXCEPTION
}
