package com.microservices.notificationservice.enums;

public enum ErrorCode {
    PAYMENT_NOT_FOUND_EXCEPTION,
    PAYMENT_ALREADY_EXISTS_EXCEPTION,
    PAYMENT_ALREADY_REFUNDED_EXCEPTION,
    PAYMENT_CANNOT_BE_REFUNDED_EXCEPTION,
    METHOD_ARGUMENT_NOT_VALID_EXCEPTION,
    CONSTRAINT_VIOLATION_EXCEPTION,
    FEIGN_CLIENT_EXCEPTION,
    SERVICE_UNAVAILABLE,
    GENERIC_EXCEPTION,
    // AWS SES
    AWS_SDK_CLIENT_EXCEPTION,
    AWS_SERVICE_EXCEPTION,
    AWS_SES_MESSAGE_REJECTED_EXCEPTION,
    AWS_SES_BAD_REQUEST_EXCEPTION,
    AWS_SES_LIMIT_EXCEEDED_EXCEPTION,
    AWS_SES_MAIL_FROM_DOMAIN_NOT_VERIFIED_EXCEPTION,
    AWS_SES_CONFIGURATION_EXCEPTION,
}