package com.microservices.notificationservice.enums;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_CANCELLATION,
    BOOKING_REMINDER,
    BOOKING_EXPIRATION,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    BOOKING_ALREADY_REFUNDED,
    BOOKING_ALREADY_CONFIRMED_NOT_ELIGIBLE_FOR_REFUND,
    BOOKING_REFUND_SUCCESS,
    BOOKING_CANCELLATION_NOT_ELIGIBLE_AS_BOOKING_NOT_CONFIRMED,
    BOOKING_IN_PENDING_STATE_DUE_TO_PAYMENT_FAILURE_RETRY_ALLOWED,
    BOOKING_FAILED_DUE_TO_PAYMENT_SERVICE_FAILURE,
    BOOKING_CANCELLATION_DUE_TO_MAX_ATTEMPTS_FOR_PAYMENT_EXHAUSTED,
    BOOKING_CANCELLATION_DUE_PAYMENT_WINDOW_EXPIRED,
    PAYMENT_FAILURE_IN_RETRY_ATTEMPT,
    BOOKING_CHECKED_IN,
    BOOKING_CHECKED_OUT,
    BOOKING_FAILED
}

