package com.microservices.bookingservice.enums;

public enum ErrorCode {
    PAYMENT_NOT_FOUND_EXCEPTION,
    PAYMENT_ALREADY_EXISTS_EXCEPTION,
    PAYMENT_ALREADY_REFUNDED_EXCEPTION,
    PAYMENT_CANNOT_BE_REFUNDED_EXCEPTION,
    METHOD_ARGUMENT_NOT_VALID_EXCEPTION,
    CONSTRAINT_VIOLATION_EXCEPTION,
    FEIGN_CLIENT_EXCEPTION,
    SERVICE_UNAVAILABLE,
    GENERIC_EXCEPTION
}
