#server:
#  port: 8080
logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
spring:
  application:
    name: USER-SERVICE
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8091

#  datasource:
#    url: jdbc:mysql://localhost:3306/userservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: Pass@123
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
#    open-in-view: false
#
#    properties:
#      hibernate:
#        format_sql: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  instance:
#    prefer-ip-address: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#  info:
#    env:
#      enabled: true

#info:
#  app:
#    name: USER-SERVICE
#    description: User Service API
#    version: 1.0


# Resilience4j Circuit Breaker Configuration
# ------------------------------------------
# Circuit Breaker protects our service from repeatedly calling
# a failing external service (e.g., Rating Service, Hotel Service).
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#
#        # Exposes Circuit Breaker status through Actuator endpoints.
#        # Example: /actuator/health
#        registerHealthIndicator: true
#
#        # Number of Circuit Breaker events stored in memory.
#        # Useful for monitoring and debugging.
#        eventConsumerBufferSize: 10
#
#        # Failure percentage required to OPEN the circuit.
#        # Example:
#        # 10 requests -> 5 fail -> 50% failure rate
#        # Circuit becomes OPEN.
#        failureRateThreshold: 50
#
#        # Minimum requests required before calculating failure rate.
#        # Prevents opening the circuit based on too few requests.
#        minimumNumberOfCalls: 5
#
#        # Automatically move from OPEN -> HALF_OPEN
#        # after waitDurationInOpenState expires.
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#
#        # Time circuit remains OPEN.
#        # During this period all requests are blocked
#        # and fallback method is executed.
#        waitDurationInOpenState: 10s
#
#        # Number of test requests allowed in HALF_OPEN state.
#        # If these succeed, circuit becomes CLOSED.
#        # If they fail, circuit returns to OPEN.
#        permittedNumberOfCallsInHalfOpenState: 3
#
#        # Number of requests considered for failure calculation.
#        # Circuit analyzes the last 10 requests.
##        slidingWindowSize: 10
#
#        # COUNT_BASED = evaluate last N requests.
#        # TIME_BASED  = evaluate requests within a time duration.
##        slidingWindowType: COUNT_BASED
#
## Actuator Configuration
## ----------------------
## Used for monitoring application health and circuit breaker status.
#
##management:
##  health:
##    circuitbreakers:
#
#      # Enables circuit breaker information in health endpoint.
#      enabled: true
#
#  endpoints:
#    web:
#      exposure:
#
#        # Expose actuator endpoints over HTTP.
#        # health  -> application health
#        # info    -> application information
#        # metrics -> application metrics
#        include: health,info,metrics
#
#  endpoint:
#    health:
#
#      # Show complete health details instead of only UP/DOWN.
#      show-details: always

#  CLOSED
#  |
#  | (Failure Rate > 50%)
#  v
#  OPEN
#  |
#  | (Wait 10 seconds)
#  v
#  HALF_OPEN
#  |
#  | (3 test requests succeed)
#  v
#  CLOSED
#
#  HALF_OPEN
#  |
#  | (Any test request fails)
#  v
#  OPEN

resilience4j:
  ratelimiter:
    instances:
      getSingleUserRateLimiter:

          # Number of requests allowed per refresh period , Defines how many requests are allowed during one refresh cycle.
        limitForPeriod: 5

            # Refresh period , Defines when the request counter resets. eg after every 10sec
        limitRefreshPeriod: 10s

            # Time to wait for permission , Defines how long a request should wait if no permission is available.
  #      ase 2:
  #        timeoutDuration: 5s
  #      timeoutDuration: 5s
  #      All permissions consumed
  #
  #      Request 6
  #      |
  #      Wait up to 5 seconds
  #      |
  #      Permission available?
  #      |
  #      YES -> Execute
  #      NO  -> Reject
        timeoutDuration: 0s
  retry:
    aspect:
      order: 1                     # Retry runs first
    instances:
      getSingleUserRetry:
        maxAttempts: 3
        waitDuration: 2s
#  circuitbreaker:
#    aspect:
#      order: 2                     # CircuitBreaker runs inside Retry
#    instances:
#      getSingleUserBreaker:
#        registerHealthIndicator: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#
#  slidingWindowSize           -> How many requests to watch
#  minimumNumberOfCalls        -> When to start watching
#  failureRateThreshold        -> When to open circuit
#  waitDurationInOpenState     -> How long to stay open
#  permittedCallsInHalfOpen    -> How many test requests
#  registerHealthIndicator     -> Show status in Actuator
#resilience4j:
#  retry:
#    instances:
#      getSingleUserRetry:
#
#        # Maximum number of attempts including the initial call.
#        # Example:
#        # Attempt 1 + Retry 1 + Retry 2 = 3 total attempts
#        maxAttempts: 3
#
#        # Wait time between retry attempts.
#        waitDuration: 2s
#
#  #        # Exceptions for which retry should happen.
#  #        retryExceptions:
#  #          - java.io.IOException
#  #          - java.util.concurrent.TimeoutException
#  #          - org.springframework.web.client.ResourceAccessException
#  #          - feign.FeignException
#  #          - feign.RetryableException
#
#  #        # Exceptions for which retry should NOT happen.
#  #        ignoreExceptions:
#  #          - java.lang.IllegalArgumentException
#
  circuitbreaker:
    instances:
      getSingleUserBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always