jwt:
  secret-key: "ThisIsMySuperSecretKeyForJWTAuthentication123456789"
  expiration: 300000

server:
    port: 8087
    servlet:
        context-path: "/api/v1"

spring:
  application:
    name: NOTIFICATION-SERVICE
  profiles:
      active: dev
  config:
      import: optional:configserver:http://localhost:8084


aws:
  region: ap-south-1
  ses:
    from-email-address: "abhishek.kanade.dev@gmail.com"
    to-addresses: "abhishek.kanade.dev@gmail.com"

    ## from-email: ${AWS_SES_FROM_EMAIL}
